# Generated by Django 6.0.4 on 2026-05-03 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0002_repair_notification_table"),
    ]

    operations = [
        migrations.AddField(
            model_name="applicationdocuments",
            name="non_creamy_layer_cert",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
