# Generated by Django 5.1.2 on 2025-10-20 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
        ('scholarships', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='financerecord',
            name='application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finance_records', to='scholarships.application'),
        ),
    ]
