# Generated by Django 4.2 on 2026-01-11 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DigiLockerRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("aadhaar", models.CharField(max_length=12, unique=True)),
                ("income_certificate_no", models.CharField(max_length=50)),
                ("caste_certificate_no", models.CharField(max_length=50)),
                ("domicile_certificate_no", models.CharField(max_length=50)),
            ],
        ),
    ]
