# Generated by Django 6.0.4 on 2026-05-03 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("digilocker_mock", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="digilockerrecord",
            name="non_creamy_layer_certificate_no",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
