# Generated by Django 4.2 on 2026-01-11 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_studentprofile"),
    ]

    operations = [
        migrations.RenameField(
            model_name="studentprofile",
            old_name="user",
            new_name="student",
        ),
        migrations.RemoveField(
            model_name="studentprofile",
            name="created_at",
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="caste",
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="course",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="district",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="gender",
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="hostel",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="income",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="institute",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="last_qualification",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="pincode",
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="state",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="year",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="studentprofile",
            name="address",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="studentprofile",
            name="dob",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="studentprofile",
            name="email",
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="studentprofile",
            name="mobile",
            field=models.CharField(max_length=10, null=True),
        ),
    ]
