# Generated by Django 6.0.4 on 2026-05-01 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_user_studentprofile_student_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='caste_cert',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='domicile_cert',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='income_cert',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
    ]
