# Generated by Django 4.2 on 2026-02-05 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("institutes", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="InstituteStudent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("aadhaar", models.CharField(max_length=12)),
                ("student_name", models.CharField(max_length=100)),
                ("course", models.CharField(max_length=100)),
                ("year", models.IntegerField()),
                (
                    "institute",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="institutes.institute",
                    ),
                ),
            ],
            options={
                "unique_together": {("institute", "aadhaar")},
            },
        ),
    ]
