# Generated by Django 4.2 on 2026-01-11 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AppliSarkarRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("aadhaar", models.CharField(max_length=12, unique=True)),
                ("domicile_state", models.CharField(max_length=50)),
                ("is_fraud", models.BooleanField(default=False)),
                ("previous_scholarship", models.BooleanField(default=False)),
            ],
        ),
    ]
